<a href="https://colab.research.google.com/github/Namesakenberg/Hyperparameter-Hangout/blob/main/Pandas_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [91]:
import pandas as pd

In [ ]:
df =pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],columns=["A","B","C"],index=["X","Y","Z"])
# creating a data frame , a data frame is the simplest datatype in pandas it is used for data anlysis and manipulation
# a dataframe is 2D,mutable and heterogeneous data structure

In [ ]:
df.head(2)
# head prints first 5 entries of the dataset

   A  B  C
X  1  2  3
Y  4  5  6

In [ ]:
df.tail(2)
# tail prints the last 5 entries of the dataframe

   A  B  C
Y  4  5  6
Z  7  8  9

In [ ]:
df.columns
# guves the names of the columns in the dataframe as a list and gives its datatype

Index(['A', 'B', 'C'], dtype='object')

In [ ]:
df.index
# index is a label which identifies each row in the datset

Index(['X', 'Y', 'Z'], dtype='object')

In [ ]:
df.info()
# info gives all the information about the coulumns , datatypes , number of entries and counts in the dataframe

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, X to Z
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 96.0+ bytes

In [ ]:
df.describe()
# the describe function is used to find all the statistical measeures of the dataset

         A    B    C
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

In [ ]:
df.nunique()
# the number unique counts the number of unique values in the columns

A    3
B    3
C    3
dtype: int64

In [ ]:
df.shape
# gives number of rows and columns in the datframe in the form of tuple , hence when calling it we dont use () at the end , as tuples cannot be called

(3, 3)

In [ ]:
df.size
# number of elements in the data set , returns int hnce it is also not callable

9

Working on a small datset

In [110]:
coffee = pd.read_csv('/coffee_small.csv')
coffee.head()
# file is of the type csv(comma separated values)
# csv files areeasy to reat manually in the raw menu , but are really huge in size

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [111]:
coffee
# to print the entire dataset just write the name

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

loc and iloc

In [112]:
# loc stands for location and is used for label based indexing to access specific rows and columns in a dataframe.

In [113]:
# coffee.loc[rows , columns]
coffee.loc[[0,5],"Day"]
# get info only about the rows and columns entered

0       Monday
5    Wednesday
Name: Day, dtype: object

In [114]:
# df.iloc[index of row , index of columns]
coffee.iloc[[1],[1,2]]
# iloc stands for index locations and only works if the index is given
# # get info only about the rows and columns entered

  Coffee Type  Units Sold
1       Latte          15

In [115]:
coffee["Day"]

0        Monday
1        Monday
2       Tuesday
3       Tuesday
4     Wednesday
5     Wednesday
6      Thursday
7      Thursday
8        Friday
9        Friday
10     Saturday
11     Saturday
12       Sunday
13       Sunday
Name: Day, dtype: object

In [116]:
coffee.at[0,"Units Sold"]
# get a single value

25

In [117]:
coffee.iat[0,2]
# integer at

25

In [118]:
coffee.sort_values(['Day','Coffee Type'],ascending=True)
# sort_values is used to sort the values wrt columns

          Day Coffee Type  Units Sold
8      Friday    Espresso          45
9      Friday       Latte          35
0      Monday    Espresso          25
1      Monday       Latte          15
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35
6    Thursday    Espresso          40
7    Thursday       Latte          30
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25

In [134]:
import numpy as np

# create a column to give price
coffee["price"]=3.50
# the same price is given to both the latte and espresso

# make new column to give price of 3.50 to latte else 4
coffee["new_price"]=np.where(coffee["Coffee Type"]=="Latte",5.99,3.99)

In [135]:
coffee.head()

,Day,Coffee Type,Units Sold,new_price,revenue,yesterday_revenue,price
0,Monday,Espresso,NaN,3.99,NaN,NaN,3.5
1,Monday,Latte,NaN,5.99,NaN,99.75,3.5
2,Tuesday,Espresso,30.0,3.99,119.70,89.85,3.5
3,Tuesday,Latte,20.0,5.99,119.80,119.70,3.5
4,Wednesday,Espresso,35.0,3.99,139.65,119.80,3.5

In [136]:
# remove the older price column
coffee=coffee.drop(columns=['price'])

In [132]:
# add a new revenue column
coffee["revenue"]=coffee['Units Sold']*coffee['new_price']

In [137]:
coffee.rename(columns={'new_price':'price'})
# rename the column 'new price' to 'price'

          Day Coffee Type  Units Sold  price  revenue  yesterday_revenue
0      Monday    Espresso         NaN   3.99      NaN                NaN
1      Monday       Latte         NaN   5.99      NaN              99.75
2     Tuesday    Espresso        30.0   3.99   119.70              89.85
3     Tuesday       Latte        20.0   5.99   119.80             119.70
4   Wednesday    Espresso        35.0   3.99   139.65             119.80
5   Wednesday       Latte        25.0   5.99   149.75             139.65
6    Thursday    Espresso        40.0   3.99   159.60             149.75
7    Thursday       Latte        30.0   5.99   179.70             159.60
8      Friday    Espresso        45.0   3.99   179.55             179.70
9      Friday       Latte        35.0   5.99   209.65             179.55
10   Saturday    Espresso        45.0   3.99   179.55             209.65
11   Saturday       Latte        35.0   5.99   209.65             179.55
12     Sunday    Espresso        45.0   3.99   179.55             209.65
13     Sunday       Latte        35.0   5.99   209.65             179.55

In [138]:
# handling the null values
# to handle , adding some null values to the data
coffee.loc[[0,1],'Units Sold']=np.nan

In [139]:
coffee
# now the first 2 values are NaN

          Day Coffee Type  Units Sold  new_price  revenue  yesterday_revenue
0      Monday    Espresso         NaN       3.99      NaN                NaN
1      Monday       Latte         NaN       5.99      NaN              99.75
2     Tuesday    Espresso        30.0       3.99   119.70              89.85
3     Tuesday       Latte        20.0       5.99   119.80             119.70
4   Wednesday    Espresso        35.0       3.99   139.65             119.80
5   Wednesday       Latte        25.0       5.99   149.75             139.65
6    Thursday    Espresso        40.0       3.99   159.60             149.75
7    Thursday       Latte        30.0       5.99   179.70             159.60
8      Friday    Espresso        45.0       3.99   179.55             179.70
9      Friday       Latte        35.0       5.99   209.65             179.55
10   Saturday    Espresso        45.0       3.99   179.55             209.65
11   Saturday       Latte        35.0       5.99   209.65             179.55
12     Sunday    Espresso        45.0       3.99   179.55             209.65
13     Sunday       Latte        35.0       5.99   209.65             179.55

In [140]:
# now to replace the values we can use
coffee.fillna(coffee['Units Sold'].mean())
# replaced the nan walves with the mean of the

          Day Coffee Type  Units Sold  new_price  revenue  yesterday_revenue
0      Monday    Espresso        35.0       3.99    35.00              35.00
1      Monday       Latte        35.0       5.99    35.00              99.75
2     Tuesday    Espresso        30.0       3.99   119.70              89.85
3     Tuesday       Latte        20.0       5.99   119.80             119.70
4   Wednesday    Espresso        35.0       3.99   139.65             119.80
5   Wednesday       Latte        25.0       5.99   149.75             139.65
6    Thursday    Espresso        40.0       3.99   159.60             149.75
7    Thursday       Latte        30.0       5.99   179.70             159.60
8      Friday    Espresso        45.0       3.99   179.55             179.70
9      Friday       Latte        35.0       5.99   209.65             179.55
10   Saturday    Espresso        45.0       3.99   179.55             209.65
11   Saturday       Latte        35.0       5.99   209.65             179.55
12     Sunday    Espresso        45.0       3.99   179.55             209.65
13     Sunday       Latte        35.0       5.99   209.65             179.55

In [141]:
# another way is to use the dropna but doing that will drop the entire row in which the null values are there
coffee.dropna()

          Day Coffee Type  Units Sold  new_price  revenue  yesterday_revenue
2     Tuesday    Espresso        30.0       3.99   119.70              89.85
3     Tuesday       Latte        20.0       5.99   119.80             119.70
4   Wednesday    Espresso        35.0       3.99   139.65             119.80
5   Wednesday       Latte        25.0       5.99   149.75             139.65
6    Thursday    Espresso        40.0       3.99   159.60             149.75
7    Thursday       Latte        30.0       5.99   179.70             159.60
8      Friday    Espresso        45.0       3.99   179.55             179.70
9      Friday       Latte        35.0       5.99   209.65             179.55
10   Saturday    Espresso        45.0       3.99   179.55             209.65
11   Saturday       Latte        35.0       5.99   209.65             179.55
12     Sunday    Espresso        45.0       3.99   179.55             209.65
13     Sunday       Latte        35.0       5.99   209.65             179.55

In [142]:
coffee.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Day                14 non-null     object
 1   Coffee Type        14 non-null     object
 2   Units Sold         12 non-null     float64
 3   new_price          14 non-null     float64
 4   revenue            12 non-null     float64
 5   yesterday_revenue  13 non-null     float64
dtypes: float64(4), object(2)
memory usage: 800.0+ bytes

In [105]:
# advanced pandas functions
# .shift() , .rank() , .rolling() , .cumsum()

In [143]:
coffee['yesterday_revenue']=coffee['revenue'].shift(1)
coffee

          Day Coffee Type  Units Sold  new_price  revenue  yesterday_revenue
0      Monday    Espresso         NaN       3.99      NaN                NaN
1      Monday       Latte         NaN       5.99      NaN                NaN
2     Tuesday    Espresso        30.0       3.99   119.70                NaN
3     Tuesday       Latte        20.0       5.99   119.80             119.70
4   Wednesday    Espresso        35.0       3.99   139.65             119.80
5   Wednesday       Latte        25.0       5.99   149.75             139.65
6    Thursday    Espresso        40.0       3.99   159.60             149.75
7    Thursday       Latte        30.0       5.99   179.70             159.60
8      Friday    Espresso        45.0       3.99   179.55             179.70
9      Friday       Latte        35.0       5.99   209.65             179.55
10   Saturday    Espresso        45.0       3.99   179.55             209.65
11   Saturday       Latte        35.0       5.99   209.65             179.55
12     Sunday    Espresso        45.0       3.99   179.55             209.65
13     Sunday       Latte        35.0       5.99   209.65             179.55

In [145]:
coffee['percent_change']=coffee['revenue']/coffee['yesterday_revenue']
coffee

,Day,Coffee Type,Units Sold,new_price,revenue,yesterday_revenue,percent_change
0,Monday,Espresso,NaN,3.99,NaN,NaN,NaN
1,Monday,Latte,NaN,5.99,NaN,NaN,NaN
2,Tuesday,Espresso,30.0,3.99,119.70,NaN,NaN
3,Tuesday,Latte,20.0,5.99,119.80,119.70,1.000835
4,Wednesday,Espresso,35.0,3.99,139.65,119.80,1.165693
5,Wednesday,Latte,25.0,5.99,149.75,139.65,1.072324
6,Thursday,Espresso,40.0,3.99,159.60,149.75,1.065776
7,Thursday,Latte,30.0,5.99,179.70,159.60,1.125940
8,Friday,Espresso,45.0,3.99,179.55,179.70,0.999165
9,Friday,Latte,35.0,5.99,209.65,179.55,1.167641
10,Saturday,Espresso,45.0,3.99,179.55,209.65,0.856427
11,Saturday,Latte,35.0,5.99,209.65,179.55,1.167641
12,Sunday,Espresso,45.0,3.99,179.55,209.65,0.856427
13,Sunday,Latte,35.0,5.99,209.65,179.55,1.167641

Working on the olympics dataset

In [93]:
results = pd.read_parquet('/results.parquet')
results.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,17.0,True,None
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,None
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,32.0,True,None
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,None
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,None

In [94]:
bios=pd.read_csv('/bios.csv')
bios.head()
# data set contains the information of the olympic athletes

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [9]:
bios.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   athlete_id    145500 non-null  int64
 1   name          145500 non-null  object
 2   born_date     143693 non-null  object
 3   born_city     110908 non-null  object
 4   born_region   110908 non-null  object
 5   born_country  110908 non-null  object
 6   NOC           145499 non-null  object
 7   height_cm     106651 non-null  float64
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   object
dtypes: float64(2), int64(1), object(7)
memory usage: 11.1+ MB

Filtering on the basis of height and weight

In [10]:
# find the athletes taller than 200cm
bios.loc[(bios['height_cm']>200) & (bios['born_country']=='USA')]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
5197,5216,Anne Donovan,1961-11-01,Ridgewood,New Jersey,USA,United States,203.0,62.0,2018-06-13
5652,5675,Mike Bantom,1951-12-03,Philadelphia,Pennsylvania,USA,United States,203.0,93.0,NaN
5657,5680,Jim Barnes,1941-04-13,Tuckerman,Arkansas,USA,United States,201.0,109.0,2002-09-14
5681,5704,Walt Bellamy,1937-07-24,New Bern,North Carolina,USA,United States,211.0,98.0,2013-11-02
5709,5732,Larry Bird,1956-12-07,French Lick,Indiana,USA,United States,205.0,100.0,NaN
...,...,...,...,...,...,...,...,...,...,...
143706,147361,Bam Adebayo,1997-07-18,Newark,New Jersey,USA,United States,206.0,116.0,NaN
143707,147362,Jerami Grant,1994-03-12,Portland,Oregon,USA,United States,203.0,95.0,NaN
143710,147365,Khris Middleton,1991-08-12,Charleston,South Carolina,USA,United States,201.0,101.0,NaN
143712,147367,JaVale McGee,1988-01-19,Flint,Michigan,USA,United States,213.0,NaN,NaN
143733,147388,Nick Allen,1998-10-08,San Diego,California,USA,United States,203.0,NaN,NaN

In [11]:
# make a column to store the first name of the athlete
# from the full name as it has spaces split it and retrun the part before space
bios['fname']=bios['name'].str.split(' ').str[0]

In [17]:
import pandas as pd

# Convert 'born_date' column to datetime format
bios['born_date'] = pd.to_datetime(bios['born_date'])

# Extract the year and store it in 'born_year'
bios['born_year'] = bios['born_date'].dt.year

In [18]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,fname,born_year
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886.0
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,1969.0
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,1898.0
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895.0
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,1878.0

In [19]:
bios.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 12 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   athlete_id    145500 non-null  int64
 1   name          145500 non-null  object
 2   born_date     143693 non-null  datetime64[ns]
 3   born_city     110908 non-null  object
 4   born_region   110908 non-null  object
 5   born_country  110908 non-null  object
 6   NOC           145499 non-null  object
 7   height_cm     106651 non-null  float64
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   object
 10  fname         145500 non-null  object
 11  born_year     143693 non-null  float64
dtypes: datetime64[ns](1), float64(3), int64(1), object(7)
memory usage: 13.3+ MB

In [20]:
# classify the athletes int short , avg and long on the basis of their height
bios['height_category']=bios['height_cm'].apply(lambda x:'short' if x<165 else ('avg' if x<185 else'Tall'))

In [21]:
bios[bios['born_country'].isin(["USA","GBR","FRA"]) & (bios['name'].str.startswith("Keith"))]
#find people from countries gbr , fra and usa having name starting with 'Keith

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,fname,born_year,height_category
3505,3517,Keith Wallace,1961-03-29,Preston,England,GBR,Great Britain,165.0,51.0,1999-12-31,Keith,1961.0,avg
12053,12118,Keith Hervey,1898-11-03,Fulham,England,GBR,Great Britain,NaN,NaN,1973-02-22,Keith,1898.0,Tall
14577,14674,Keith Harrison,1933-03-28,Birmingham,England,GBR,Great Britain,NaN,NaN,NaN,Keith,1933.0,Tall
16166,16281,Keith Reynolds,1963-12-25,Solihull,England,GBR,Great Britain,173.0,68.0,NaN,Keith,1963.0,avg
18734,18862,Keith Sinclair,1945-06-26,Sunderland,England,GBR,Great Britain,190.0,79.0,NaN,Keith,1945.0,Tall
29897,30123,Keith Langley,1961-06-03,Aldershot,England,GBR,Great Britain,173.0,70.0,NaN,Keith,1961.0,avg
34011,34275,Keith Remfry,1947-11-17,Ealing,England,GBR,Great Britain,193.0,114.0,2015-09-16,Keith,1947.0,Tall
46885,47234,Keith Collin,1937-01-18,Marylebone,England,GBR,Great Britain,168.0,63.0,1991-03-06,Keith,1937.0,avg
50929,51288,Keith Carter,1924-08-30,Akron,Ohio,USA,United States,NaN,NaN,2013-05-03,Keith,1924.0,Tall
51185,51544,Keith Russell,1948-01-15,Mesa,Arizona,USA,United States,188.0,73.0,NaN,Keith,1948.0,Tall
52913,53288,Keith Erickson,1944-04-19,San Francisco,California,USA,United States,196.0,86.0,NaN,Keith,1944.0,Tall
55317,55712,Keith Boxell,1958-05-06,Clapham,England,GBR,Great Britain,170.0,87.0,NaN,Keith,1958.0,avg
57818,58226,Keith Peache,1947-08-10,Lewisham,England,GBR,Great Britain,180.0,98.0,NaN,Keith,1947.0,avg
61748,62202,Keith Grogono,1912-11-04,Stratford,England,GBR,Great Britain,NaN,NaN,1999-03-22,Keith,1912.0,Tall
62620,63086,Keith Musto,1936-01-12,Rochford,England,GBR,Great Britain,174.0,72.0,NaN,Keith,1936.0,avg
62678,63144,Keith Notary,1960-01-22,Merritt Island,Florida,USA,United States,170.0,66.0,NaN,Keith,1960.0,avg
68324,68841,Keith Angus,1943-04-05,Sheffield,England,GBR,Great Britain,170.0,59.0,NaN,Keith,1943.0,avg
68472,68989,Keith Cullen,1972-06-13,Ilford,England,GBR,Great Britain,177.0,61.0,NaN,Keith,1972.0,avg
68997,69514,Keith Stock,1957-03-18,Woolwich,England,GBR,Great Britain,176.0,73.0,NaN,Keith,1957.0,avg
77550,78141,Keith Brantly,1962-05-23,Scott Air Force Base,Illinois,USA,United States,180.0,64.0,NaN,Keith,1962.0,avg
84097,84766,Keith Christiansen,1944-07-14,International Falls,Minnesota,USA,United States,165.0,69.0,2018-11-05,Keith,1944.0,avg
94646,95413,Keith Meyer,1938-06-20,Geneva,Illinois,USA,United States,NaN,NaN,2010-07-25,Keith,1938.0,Tall
95267,96037,Keith Oliver,1947-10-27,Liverpool,England,GBR,Great Britain,172.0,68.0,NaN,Keith,1947.0,avg
96452,97229,Keith Schellenberg,1929-03-13,Middlesbrough,England,GBR,Great Britain,NaN,NaN,2019-10-28,Keith,1929.0,Tall
97499,98286,Keith Tkachuk,1972-03-28,Melrose,Massachusetts,USA,United States,188.0,102.0,NaN,Keith,1972.0,Tall
98068,98860,Keith Wegeman,1929-08-28,Denver,Colorado,USA,United States,NaN,NaN,1974-08-22,Keith,1929.0,Tall
99921,100722,Keith Carney,1970-02-03,Providence,Rhode Island,USA,United States,188.0,93.0,NaN,Keith,1970.0,Tall
115973,117348,Keith Sanderson,1975-02-02,Plymouth,Massachusetts,USA,United States,183.0,95.0,NaN,Keith,1975.0,avg

In [22]:
# only print the players with small height
bios[bios['height_category']=='short']

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,fname,born_year,height_category
49,50,Gillian Gowers,1964-04-09,NaN,NaN,NaN,Great Britain,157.0,55.0,NaN,Gillian,1964.0,short
62,63,Jo Muggeridge,1969-04-03,London,England,GBR,Great Britain,157.0,59.0,NaN,Jo,1969.0,short
128,129,Olga Nemes,1968-06-09,Târgu Mureș,Mureș,ROU,Germany West Germany,163.0,53.0,NaN,Olga,1968.0,short
171,172,Christina Zachariadou,1974-08-28,Athina (Athens),Attiki,GRE,Greece,163.0,57.0,NaN,Christina,1974.0,short
192,193,Hui So Hung,1958-12-02,NaN,NaN,NaN,"Hong Kong, China",160.0,57.0,NaN,Hui,1958.0,short
...,...,...,...,...,...,...,...,...,...,...,...,...,...
144989,148700,Lotta Udnes Weng,1996-09-29,Lørenskog,Viken,NOR,Norway,151.0,NaN,NaN,Lotta,1996.0,short
144995,148706,Sandra Eie,1995-11-14,Oslo,Oslo,NOR,Norway,158.0,NaN,NaN,Sandra,1995.0,short
145096,148809,Kamila Valiyeva,2006-04-26,Kazan,Respublika Tatarstan,RUS,ROC,160.0,NaN,NaN,Kamila,2006.0,short
145474,149201,Nadine Hofstetter,1994-10-21,Romoos,Luzern,SUI,Switzerland,164.0,68.0,NaN,Nadine,1994.0,short
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN,Yuliya,1998.0,short

In [23]:
bios.query('born_country=="USA" and born_city=="Seattle"')
# use the query function to find the people living in a specific city of a speciific country

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,fname,born_year,height_category
11030,11088,David Halpern,1955-08-18,Seattle,Washington,USA,United States,178.0,79.0,NaN,David,1955.0,avg
12800,12870,Todd Trewin,1958-04-20,Seattle,Washington,USA,United States,180.0,75.0,NaN,Todd,1958.0,avg
15476,15583,Scott McKinley,1968-10-15,Seattle,Washington,USA,United States,183.0,75.0,NaN,Scott,1968.0,avg
29079,29293,Joyce Tanac,1950-09-27,Seattle,Washington,USA,United States,156.0,49.0,NaN,Joyce,1950.0,short
31135,31371,Bill Kuhlemeier,1908-01-14,Seattle,Washington,USA,United States,NaN,NaN,2001-07-08,Bill,1908.0,Tall
...,...,...,...,...,...,...,...,...,...,...,...,...,...
133392,136331,Hans Struzyna,1989-03-31,Seattle,Washington,USA,United States,188.0,91.0,NaN,Hans,1989.0,Tall
135448,138662,Maude Davis Crossland,2003-03-19,Seattle,Washington,USA,Colombia,NaN,NaN,NaN,Maude,2003.0,Tall
136993,140229,Jenell Berhorst,2003-12-13,Seattle,Washington,USA,United States,NaN,NaN,NaN,Jenell,2003.0,Tall
143507,147159,Nevin Harrison,2002-06-02,Seattle,Washington,USA,United States,175.0,73.0,NaN,Nevin,2002.0,avg
145446,149169,Corinne Stoddard,2001-08-15,Seattle,Washington,USA,United States,NaN,NaN,NaN,Corinne,2001.0,Tall

In [ ]:
# get a sub data set of the bios
# this sub data set contains only the name and the NOC column from the above data set

In [24]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,fname,born_year,height_category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886.0,Tall
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,1969.0,avg
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,1898.0,avg
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895.0,avg
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,1878.0,Tall

In [95]:
nocs = pd.read_csv('/noc_regions.csv')
nocs.head()

   NOC       region                 notes
0  AFG  Afghanistan                   NaN
1  AHO      Curacao  Netherlands Antilles
2  ALB      Albania                   NaN
3  ALG      Algeria                   NaN
4  AND      Andorra                   NaN

In [27]:
# merging the bios dataset with the noc data set

In [28]:
bios_new=pd.merge(bios, nocs, left_on='born_country', right_on='NOC',how='left',suffixes=non)

In [32]:
bios.head(10)

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,fname,born_year,height_category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886.0,Tall
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,1969.0,avg
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,1898.0,avg
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895.0,avg
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,1878.0,Tall
5,6,Nicolas Chatelain,1970-01-13,Amiens,Somme,FRA,France,181.0,70.0,NaN,Nicolas,1970.0,avg
6,7,Patrick Chila,1969-11-27,Ris-Orangis,Essonne,FRA,France,180.0,73.0,NaN,Patrick,1969.0,avg
7,8,Henri Cochet,1901-12-14,Villeurbanne,Rhône,FRA,France,NaN,NaN,1987-04-02,Henri,1901.0,Tall
8,9,Marcel Cousin,1896-08-04,Nîmes,Gard,FRA,France,NaN,NaN,1986-08-01,Marcel,1896.0,Tall
9,10,Guy de la Chapelle,1868-07-16,Farges-Allichamps,Cher,FRA,France,NaN,NaN,1923-08-27,Guy,1868.0,Tall

In [30]:
bios.rename(columns={'region': 'born_country_full'},inplace=True)

In [33]:
bios_new.head(10)
# the suffixes _x and _y are there as the same column was present in the 2 datasets

,athlete_id,name,born_date,born_city,born_region,born_country,NOC_x,height_cm,weight_kg,died_date,fname,born_year,height_category,NOC_y,region,notes
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886.0,Tall,FRA,France,NaN
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,1969.0,avg,FRA,France,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,1898.0,avg,FRA,France,NaN
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895.0,avg,FRA,France,NaN
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,1878.0,Tall,GBR,UK,NaN
5,6,Nicolas Chatelain,1970-01-13,Amiens,Somme,FRA,France,181.0,70.0,NaN,Nicolas,1970.0,avg,FRA,France,NaN
6,7,Patrick Chila,1969-11-27,Ris-Orangis,Essonne,FRA,France,180.0,73.0,NaN,Patrick,1969.0,avg,FRA,France,NaN
7,8,Henri Cochet,1901-12-14,Villeurbanne,Rhône,FRA,France,NaN,NaN,1987-04-02,Henri,1901.0,Tall,FRA,France,NaN
8,9,Marcel Cousin,1896-08-04,Nîmes,Gard,FRA,France,NaN,NaN,1986-08-01,Marcel,1896.0,Tall,FRA,France,NaN
9,10,Guy de la Chapelle,1868-07-16,Farges-Allichamps,Cher,FRA,France,NaN,NaN,1923-08-27,Guy,1868.0,Tall,FRA,France,NaN

In [42]:
ind = bios[bios['born_country']=='IND'].copy()
ind.tail()
# new dataframe having only the athletes born in uk

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,fname,born_year,height_category
140286,143790,Bajrang Punia,1994-02-26,Khudan,Haryana,IND,India,NaN,NaN,NaN,Bajrang,1994.0,Tall
140287,143791,Deepak Punia,1999-05-19,Jhajjar,Haryana,IND,India,NaN,NaN,NaN,Deepak,1999.0,Tall
143996,147660,Sumit Nagal,1997-08-16,Jhajjar,Haryana,IND,India,NaN,NaN,NaN,Sumit,1997.0,Tall
144114,147784,Diksha Dagar,2000-12-14,Jhajjar,Haryana,IND,India,174.0,NaN,NaN,Diksha,2000.0,avg
144757,148458,Arif Khan,1990-03-09,Gulmarg,Jammu and Kashmir,IND,India,NaN,NaN,NaN,Arif,1990.0,Tall

In [44]:
# new dataframe having athletes from usa
usa = bios[bios['born_country']=='USA'].copy()
usa.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,fname,born_year,height_category
54,55,Monique Javer,1967-07-22,Burlingame,California,USA,Great Britain,177.0,64.0,NaN,Monique,1967.0,avg
960,964,Xóchitl Escobedo,1968-09-17,West Covina,California,USA,Mexico,170.0,60.0,NaN,Xóchitl,1968.0,avg
961,965,Angélica Gavaldón,1973-10-03,El Centro,California,USA,Mexico,160.0,54.0,NaN,Angélica,1973.0,short
1231,1238,Bert Schneider,1897-07-01,Cleveland,Ohio,USA,Canada,NaN,NaN,1986-02-20,Bert,1897.0,Tall
1345,1352,Laura Berg,1975-01-06,Santa Fe Springs,California,USA,United States,168.0,61.0,NaN,Laura,1975.0,avg

In [47]:
# concatinating ind and usa
ind_usa=pd.concat([usa,ind])
ind_usa.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,fname,born_year,height_category
54,55,Monique Javer,1967-07-22,Burlingame,California,USA,Great Britain,177.0,64.0,NaN,Monique,1967.0,avg
960,964,Xóchitl Escobedo,1968-09-17,West Covina,California,USA,Mexico,170.0,60.0,NaN,Xóchitl,1968.0,avg
961,965,Angélica Gavaldón,1973-10-03,El Centro,California,USA,Mexico,160.0,54.0,NaN,Angélica,1973.0,short
1231,1238,Bert Schneider,1897-07-01,Cleveland,Ohio,USA,Canada,NaN,NaN,1986-02-20,Bert,1897.0,Tall
1345,1352,Laura Berg,1975-01-06,Santa Fe Springs,California,USA,United States,168.0,61.0,NaN,Laura,1975.0,avg

In [49]:
results.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,17.0,True,None
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,None
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,32.0,True,None
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,None
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,None

In [57]:
# now combining the bios and the results data set
combined_df = pd.merge(results,bios,on="athlete_id",how='left')
# as both the datasets have the athlete id same we combine it
combined_df.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,...,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,fname,born_year,height_category
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,17.0,True,...,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886.0,Tall
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,...,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886.0,Tall
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,32.0,True,...,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886.0,Tall
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,...,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886.0,Tall
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,...,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886.0,Tall

In [58]:
combined_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 308408 entries, 0 to 308407
Data columns (total 23 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   year             305807 non-null  float64
 1   type             305807 non-null  object
 2   discipline       308407 non-null  object
 3   event            308408 non-null  object
 4   as               308408 non-null  object
 5   athlete_id       308408 non-null  int64
 6   noc              308407 non-null  object
 7   team             121714 non-null  object
 8   place            283193 non-null  float64
 9   tied             308408 non-null  bool
 10  medal            44139 non-null   object
 11  name             308408 non-null  object
 12  born_date        305692 non-null  datetime64[ns]
 13  born_city        246890 non-null  object
 14  born_region      246890 non-null  object
 15  born_country     246890 non-null  object
 16  NOC              308408 non-null  object
 17  height_cm        236910 non-null  float64
 18  weight_kg        227290 non-null  float64
 19  died_date        73521 non-null   object
 20  fname            308408 non-null  object
 21  born_year        305692 non-null  float64
 22  height_category  308408 non-null  object
dtypes: bool(1), datetime64[ns](1), float64(5), int64(1), object(15)
memory usage: 52.1+ MB

In [ ]:
# aggregating the data

In [89]:
# getting the cities from where most athletes come from
bios['born_city'].value_counts()

born_city
Budapest           1378
Moskva (Moscow)     883
Oslo                708
Stockholm           629
Praha (Prague)      600
                   ...
Bodrogkisfalud        1
Ternberg              1
Klaus                 1
Plaški                1
Dulwich Hill          1
Name: count, Length: 22368, dtype: int64

In [104]:
# grouping people born in a specific year
bios['born_date']=pd.to_datetime(bios['born_date'])
bios['born_month']=bios['born_date'].dt.month
bios['born_year']=bios['born_date'].dt.year
bios.groupby([bios['born_year'],bios['born_month']])['name'].count().sort_values(ascending=False)

born_year  born_month
1970.0     1.0           239
1972.0     1.0           229
1986.0     1.0           227
1975.0     1.0           227
1985.0     1.0           225
                        ...
1857.0     5.0             1
           7.0             1
           8.0             1
           9.0             1
2009.0     1.0             1
Name: name, Length: 1885, dtype: int64